sudo: false
language: elixir
elixir:
#  - 1.3.1
  - 1.3.4
otp_release:
#  - 18.0
#  - 18.1
#  - 18.2
  - 19.0
services:
  - postgresql
addons:
  postgresql: "9.4"
script: mix test
after_script:
  - mix deps.get --only test
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    on_success: never
    on_failure: always
